In [7]:
#Funcion para capturar los objetos por etiqueta y clase
def buscar_issues_clase(html, clase):
    soup = BeautifulSoup(html, "html.parser")
    return soup.find_all(content= re.compile(clase +"$"))

In [10]:
from bs4 import BeautifulSoup
import pandas as pd
import re
import requests
import string

# número de issue
issue_range = 60

# definición del DataFrame
columns = ["issue", "author", "state", "assignees"]
df = pd.DataFrame(columns=columns)

for numero_issue in range(1,issue_range+1):
    # url del issue
    url_name = "https://github.com/pescap/WebScrapingMDS/issues/" + str(numero_issue)

    # Recuperar el html
    url = requests.get(url_name)  
    
    existe = buscar_issues_clase(url.content, url_name)
    
    if (len(existe)>0):  
        soup = BeautifulSoup(url.text, "html.parser")
        state = "open"
        # if encuentro un banner de estado cerrado
        #   state = "closed"

        if soup.find("span", attrs={"title": "Status: Closed"}):
            state = "closed"

        author = soup.find("a", attrs={"class": "author text-bold Link--secondary"}).get_text()
        assignees = (
            soup.find("span", attrs={"class": "css-truncate js-issue-assignees"})
            .get_text()
            .replace("\n", "")
            .split()
        )

        if assignees == ["No", "one", "assigned"]:
            assignees = ["No one assigned"]

        #print(issue, author, state, assignees)

        for l in range(len(assignees)):
            df = df.append(
                {"issue": numero_issue, "author": author, "state": state, "assignees": assignees[l]},
                ignore_index=True,
            )
    #else:
        #print(str(numero_issue)+ " no es issue")

C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(
C:\Users\carlo\AppData\Local\Temp\ipykernel_6984\4087113072.py:46: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(

In [11]:
df.count()

issue        25
author       25
state        25
assignees    25
dtype: int64

In [12]:
df

   issue                author   state             assignees
0      1                pescap    open       No one assigned
1      2                pescap  closed                pescap
2      2                pescap  closed             caspoerer
3      4                pescap  closed       No one assigned
4      5          GeorgeAdrock    open          GeorgeAdrock
5      7                pescap  closed       No one assigned
6     15            DenisOsses  closed       No one assigned
7     17  CarlosZuritaEstolaza    open  CarlosZuritaEstolaza
8     20  CarlosZuritaEstolaza    open       No one assigned
9     21              gavalenz    open       No one assigned
10    24            kevimulloa    open       No one assigned
11    25      josemoragonzalez  closed                pescap
12    25      josemoragonzalez  closed      josemoragonzalez
13    27                pescap    open       No one assigned
14    28       JoseAlexanderCL  closed       JoseAlexanderCL
15    29             iggypoprl    open       No one assigned
16    34              cechiang    open       No one assigned
17    43      DavidValenzuelaP    open       No one assigned
18    45            jwilenmann  closed       No one assigned
19    46                pescap  closed       No one assigned
20    47                pescap  closed       No one assigned
21    48           omaldonados    open       No one assigned
22    50          Carloslugook    open       No one assigned
23    54         ronaldchester    open       No one assigned
24    60         MiguelAbarzua    open       No one assigned

In [13]:
df2 = df[["author","state"]]
df2 = df2[df2["author"] != "pescap"]

In [14]:
df2.columns

Index(['author', 'state'], dtype='object')

In [15]:
agrupados = df2.groupby(['author'])['author'].count().reset_index(name='counts')

In [16]:
agrupados.sort_values("counts", ascending=False)

                  author  counts
0   CarlosZuritaEstolaza       2
10      josemoragonzalez       2
1           Carloslugook       1
2       DavidValenzuelaP       1
3             DenisOsses       1
4           GeorgeAdrock       1
5        JoseAlexanderCL       1
6          MiguelAbarzua       1
7               cechiang       1
8               gavalenz       1
9              iggypoprl       1
11            jwilenmann       1
12            kevimulloa       1
13           omaldonados       1
14         ronaldchester       1